theme: jekyll-theme-dinky

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo knowdo
subtitle:
description:
author: John Doe
language:
timezone: Asia/Shanghai
